version: '3.4'

services:
  nodefarm:
    image: nodefarm
    build:
      context: 1-node-farm/final
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
